trigger: none

pool: Default

stages:
  - stage: 
    displayName: Aks ingress deploy
    jobs:
      - job:
        displayName: Ingress deployment 
        steps:
        - task: KubernetesManifest@1
          displayName: "Deploy Ingress"
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'aks-service'
            manifests: | 
             $(Build.SourcesDirectory)/k8s/ingress.yaml
        
