apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
  namespace: satish-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
        - name: axion-ui
          image: clusteraliregistry.azurecr.io/axion-ui:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
