apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
  namespace: satish-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: telemetry
          image: clusteraliregistry.azurecr.io/telemetry:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
