apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
  # namespace: satish-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: telemetry
          image: clusteraliregistry.azurecr.io/telemetry-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
      
          # envFrom:
          #   - configMapRef:
          #       name: DATABASE_URL=postgresql://postgresadmin:airtel%40123@postgres-axion1.postgres.database.azure.com:5432/axionDB
