apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  # namespace: satish-k8s

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ingestion

  template:
    metadata:
      labels:
        app: ingestion

    spec:
      containers:
        - name: ingestion
          image: clusteraliregistry.azurecr.io/ingestion-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          # env:
          #   - name: DATABASE_URL
          #     value: "postgresql://postgresadmin:airtel%40123@postgres-axion1.postgres.database.azure.com:5432/axionDB"